# Generated by Django 4.0.2 on 2022-04-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ_model', '0002_support_writer_alter_support_created_at_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='last_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='최종 수정일시'),
        ),
    ]
